services:
  api:
    build:
      context: ../
      dockerfile: ./validator/submission_tester/Dockerfile

    volumes:
      - ~/edge-maxxing/baseline-sandbox:/baseline-sandbox

    ports:
      - 127.0.0.1:8000:8000

    deploy:
      resources:
        reservations:
          devices:
            - capabilities:
                - gpu

    healthcheck:
      test: ["curl", "http://localhost:8000/state"]
      interval: 30s
      timeout: 10s

  validator:
    build:
      context: ../
      dockerfile: ./validator/weight_setting/Dockerfile

    volumes:
      - ~/.bittensor:/home/validator/.bittensor
      - ~/.netrc:/home/validator/.netrc

    command: --benchmarker_api http://localhost:8000 $VALIDATOR_ARGS

    network_mode: host

    depends_on:
      api:
        condition: service_healthy
