[tool.poetry]
name = "edge-maxxing-validator"

version = "1.0.0"

description = "The validator which checks models and checkpoints provided by miners"

readme = "../README.md"

license = "MIT"

authors = ["WOMBO <hello@w.ai>"]

packages = [
    { include = "base_validator" },
    { include = "submission_tester" },
    { include = "weight_setting" },
]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Build Tools",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

[tool.poetry.dependencies]
python = ">=3.10,<3.13"
wandb = "0.17.8"
torch = "2.4.0"
diffusers = "0.30.2"
nltk = "3.9.1"
transformers = "4.44.2"
accelerate = "0.34.0"
omegaconf = "2.3.0"
pynvml = "11.5.3"
torchvision = "0.19.0"
edge-maxxing-pipelines = { path = "../pipelines", develop = true }
edge-maxxing-neuron = { path = "../neuron", develop = true }

[tool.poetry.scripts]
start_validator = 'weight_setting.validator:main'

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry-monorepo.deps]

[tool.pytype]
inputs = ["validator"]
