[tool.poetry]
name = "apple-silicon-training-subnet-miner"

version = "1.0.0"

description = "The miner which provides optimized models and checkpoints"

readme = "../README.md"

license = "MIT"

authors = ["WOMBO <hello@w.ai>"]

classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Topic :: Software Development :: Build Tools",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.10",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Programming Language :: Python :: 3 :: Only",
    "Topic :: Scientific/Engineering",
    "Topic :: Scientific/Engineering :: Mathematics",
    "Topic :: Scientific/Engineering :: Artificial Intelligence",
]

[tool.poetry.dependencies]
python = ">=3.10,<=3.12"
apple-silicon-training-subnet = { path = "../neuron", develop = true }
requests-toolbelt = "1.0.0"
APScheduler = "3.10.4"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
