on:
  push:
    branches:
      - main
    paths:
      - 'neuron/**'

jobs:
  test-types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Types
        working-directory: neuron
        run: |
          poetry install
          poetry run pytype
