on:
  pull_request:
    type:
      - opened
  push:
    paths:
      - 'neuron/**'
      - 'miner/**'

jobs:
  test-types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Test Types
        working-directory: miner
        run: |
          poetry install
          poetry run pytype
