name: Test Common Types

on:
  - pull_request
  - workflow_dispatch

jobs:
  test-types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install uv
        uses: astral-sh/setup-uv@v3

      - name: Test Types
        working-directory: base
        run: |
          uv run pytype
